AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.function.handler
      Runtime: nodejs18.x
      CodeUri: ./src/lambda
      Events:
        Api:
          Type: Api
          Properties:
            Path: /user
            Method: post
